### PR TITLE
fix assert on self-referencing function ptr field

### LINKED ISSUE #795: Assertion failure when declaring struct S { m: fn(self: S) }
This code:

```
const assert = @import("std").debug.assert;

const S = struct {
    a_member: u8,
    a_member_method: fn(self: S) u8,
};

fn aStructFunction(self: S) u8 { return self.a_member; }

test "namespacing" {
    const s = S {
        .a_member = 1,
        .a_member_method = aStructFunction  
    };
    assert(s.a_member_method(s) == 1);
}
```

Produces:

```
$ ~/zig/build/zig test test.zig 
zig: /home/raulgrell/zig/src/analyze.cpp:1645: void resolve_struct_type(CodeGen*, TypeTableEntry*): Assertion `!struct_type->data.structure.zero_bits_loop_flag' failed.
```

Fixed by changing original code to:

```
const assert = @import("std").debug.assert;

const S = struct {
    a_member: u8,
    a_member_method: fn(self: &const S) u8,
};

fn aStructFunction(self: &const S) u8 { return self.a_member; }

test "namespacing" {
    const s = S {
        .a_member = 1,
        .a_member_method = aStructFunction  
    };

    assert(s.a_member_method(s) == 1);
}
```

Which is arguably more correct, but the error needs improvement.

### PR DESCRIPTION
**Pull request by bnoordhuis**
The construct `struct S { f: fn(S) void }` is not legal because structs
are not copyable but it should not result in an ICE.

Fixes #795.

Best possible fix or not?  There is existing logic for detecting self-recursive types but this isn't quite that.  Suggestions welcome.

### CODE REVIEW

File: src/analyze.cpp [hunk 1]
```diff
@@ -1670,6 +1670,9 @@ static void resolve_struct_type(CodeGen *g, TypeTableEntry *struct_type) {
     if (struct_type->data.structure.is_invalid)
         return;
 
+    if (struct_type->data.structure.zero_bits_loop_flag)
```
Comment (andrewrk) [inline src/analyze.cpp]: hmm this doesn't seem right to me. if we return from `resolve_struct_zero_bits` then either `zero_bits_loop_flag` should be `false` or `is_invalid` should be `true`. Let me poke at it.

**Comment by andrewrk** [comment]
The `resolve_*_zero_bits` and `resolve_*_type` functions are brittle and I need to rework how all that is handled. My plan is to do a better implementation in the self hosted compiler and then, if necessary, port the better implementation back to the c++ compiler.
